version: "3.9"

services:
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
      target: develop
    volumes:
      - type: bind
        source: "./api/"
        target: "/usr/src/unlock-mox-si/api"
    ports:
      - target: 8080
        published: 18080
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - mongo_network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    networks:
      - mongo_network
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

networks:
  mongo_network:
